# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainText(object):
    def setupUi(self, MainText):
        MainText.setObjectName("MainText")
        MainText.resize(582, 594)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/spider.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainText.setWindowIcon(icon)
        MainText.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainText)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setMinimumSize(QtCore.QSize(50, 10))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.reset.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon1)
        self.reset.setObjectName("reset")
        self.horizontalLayout_2.addWidget(self.reset)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.extract = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.extract.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/extract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extract.setIcon(icon2)
        self.extract.setObjectName("extract")
        self.horizontalLayout_2.addWidget(self.extract)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainText.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainText)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 29))
        self.menubar.setObjectName("menubar")
        self.menusetting = QtWidgets.QMenu(self.menubar)
        self.menusetting.setObjectName("menusetting")
        self.menus = QtWidgets.QMenu(self.menubar)
        self.menus.setObjectName("menus")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainText.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainText)
        self.statusbar.setObjectName("statusbar")
        MainText.setStatusBar(self.statusbar)
        self.about = QtWidgets.QAction(MainText)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about.setIcon(icon3)
        self.about.setObjectName("about")
        self.help = QtWidgets.QAction(MainText)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help.setIcon(icon4)
        self.help.setObjectName("help")
        self.update = QtWidgets.QAction(MainText)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update.setIcon(icon5)
        self.update.setObjectName("update")
        self.once = QtWidgets.QAction(MainText)
        self.once.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/once.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.once.setIcon(icon6)
        self.once.setVisible(True)
        self.once.setObjectName("once")
        self.more = QtWidgets.QAction(MainText)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/more.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.more.setIcon(icon7)
        self.more.setObjectName("more")
        self.feedBack = QtWidgets.QAction(MainText)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/feedBack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedBack.setIcon(icon8)
        self.feedBack.setObjectName("feedBack")
        self.local = QtWidgets.QAction(MainText)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/local.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.local.setIcon(icon9)
        self.local.setObjectName("local")
        self.database = QtWidgets.QAction(MainText)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.database.setIcon(icon10)
        self.database.setObjectName("database")
        self.filePath = QtWidgets.QAction(MainText)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filePath.setIcon(icon11)
        self.filePath.setObjectName("filePath")
        self.menusetting.addAction(self.once)
        self.menusetting.addAction(self.more)
        self.menusetting.addAction(self.local)
        self.menus.addAction(self.database)
        self.menus.addAction(self.filePath)
        self.menu.addAction(self.help)
        self.menu.addAction(self.feedBack)
        self.menu_2.addAction(self.about)
        self.menu_2.addAction(self.update)
        self.menubar.addAction(self.menusetting.menuAction())
        self.menubar.addAction(self.menus.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainText)
        QtCore.QMetaObject.connectSlotsByName(MainText)

    def retranslateUi(self, MainText):
        _translate = QtCore.QCoreApplication.translate
        MainText.setWindowTitle(_translate("MainText", "MainText"))
        self.label.setText(_translate("MainText", "网页地址："))
        self.toolButton.setText(_translate("MainText", "..."))
        self.reset.setText(_translate("MainText", "重置"))
        self.extract.setText(_translate("MainText", "提取"))
        self.textBrowser.setHtml(_translate("MainText", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9.07563pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.07563pt;\">*****************</span><span style=\" font-size:9.07563pt; font-weight:600;\">日志信息</span><span style=\" font-size:9.07563pt;\">******************</span></p></body></html>"))
        self.menusetting.setTitle(_translate("MainText", "爬取方式"))
        self.menus.setTitle(_translate("MainText", "设置"))
        self.menu.setTitle(_translate("MainText", "帮助"))
        self.menu_2.setTitle(_translate("MainText", "关于"))
        self.about.setText(_translate("MainText", "关于"))
        self.about.setShortcut(_translate("MainText", "Ctrl+Q"))
        self.help.setText(_translate("MainText", "帮助"))
        self.help.setShortcut(_translate("MainText", "Ctrl+H"))
        self.update.setText(_translate("MainText", "更新"))
        self.update.setShortcut(_translate("MainText", "Ctrl+U"))
        self.once.setText(_translate("MainText", "单次爬取"))
        self.once.setShortcut(_translate("MainText", "Ctrl+O"))
        self.more.setText(_translate("MainText", "批量爬取"))
        self.more.setShortcut(_translate("MainText", "Ctrl+M"))
        self.feedBack.setText(_translate("MainText", "反馈"))
        self.feedBack.setShortcut(_translate("MainText", "Ctrl+F"))
        self.local.setText(_translate("MainText", "本地导入"))
        self.local.setShortcut(_translate("MainText", "Ctrl+L"))
        self.database.setText(_translate("MainText", "数据库"))
        self.database.setShortcut(_translate("MainText", "Ctrl+D"))
        self.filePath.setText(_translate("MainText", "文件路径"))
        self.filePath.setShortcut(_translate("MainText", "Ctrl+F"))

import images_rc
